#!/usr/bin/env bash
# Update content/INDEX.md by scanning all content markdown files.
# Generates a browsable archive index with grouping by month and file descriptions.

set -euo pipefail

WORKSPACE="/home/ubuntu/.openclaw/workspace"
CONTENT_DIR="$WORKSPACE/content"
INDEX_FILE="$CONTENT_DIR/INDEX.md"

echo "== Updating Content Archive Index =="

# Ensure content directory exists
if [ ! -d "$CONTENT_DIR" ]; then
  echo "Error: content directory not found at $CONTENT_DIR"
  exit 1
fi

# Start building new index content
cat > "$INDEX_FILE" <<'EOF'
# Content Archive Index

This directory contains daily digests, notes, and summaries generated by the `content-agent`.

## Recent Content (February 2026)

EOF

# Group files by month/year; for now assume all are 2026-02. We'll sort by date.
# Get list of .md files excluding INDEX.md itself, sorted reverse chronological (newest first)
mapfile -t files < <(ls -1t "$CONTENT_DIR"/*.md 2>/dev/null | grep -v 'INDEX.md' || true)

if [ ${#files[@]} -eq 0 ]; then
  echo "Warning: no content files found." >> "$INDEX_FILE"
else
  # For simplicity, list all files under "February 2026" section with brief description extracted from first heading.
  # We'll generate bullet list: - `filename` — description (size KB)
  for file in "${files[@]}"; do
    filename=$(basename "$file")
    # Get file size in KB (rounded)
    size=$(du -k "$file" | cut -f1)
    # Extract first markdown heading (line starting with #) or fallback to filename
    description=$(grep -m1 '^#' "$file" | sed 's/^#* //' | tr -d '\r' || echo "$filename")
    # Clean description: remove trailing punctuation, limit length
    description=$(echo "$description" | sed 's/[[:punct:]]*$//')
    if [ -z "$description" ]; then
      description="Note"
    fi
    # Append bullet
    echo "- \`$filename\` — $description ($size KB)" >> "$INDEX_FILE"
  done
fi

# Append static footer (except last updated)
cat >> "$INDEX_FILE" <<'STATIC_FOOTER'

---

## Usage

```
# List all content files (sorted by date)
ls -lt content/*.md

# Search across all digests
grep -r "query" content/*.md

# View latest digest
cat content/$(ls -t content/*.md | head -1)
```

---

## Naming Conventions

- `YYYY-MM-DD-<type>.md` — Date‑prefixed filenames
- Types: `daily-digest`, `research-index-note`, `cny-final-wrap`, `sunday-final`, etc.
- Index files: `YYYY-MM-DD-index.md` (when multiple digests per day are produced)

STATIC_FOOTER

# Append dynamic last updated line
echo "*Last updated: $(date +%Y-%m-%d)*" >> "$INDEX_FILE"

echo "✅ Content index updated: $INDEX_FILE"
echo "   Tracked ${#files[@]} content files."
