#!/usr/bin/env bash
# Monthly Digest Generator — aggregates daily digests for a given month
# usage: scripts/generate-monthly-digest.sh [YYYY-MM] (defaults to current month UTC)

set -euo pipefail
cd /home/ubuntu/.openclaw/workspace

MONTH="${1:-$(date -u +%Y-%m)}"
REPORT_DIR="reports"
mkdir -p "$REPORT_DIR"
REPORT_FILE="${REPORT_DIR}/${MONTH}-monthly-digest.md"

# Validate format
if ! [[ "$MONTH" =~ ^[0-9]{4}-[0-9]{2}$ ]]; then
  echo "Error: month must be in YYYY-MM format"
  exit 1
fi

# Collect daily digest files for this month
mapfile -t DAILY_FILES < <(find reports/ -maxdepth 1 -name "${MONTH}*-daily-digest.md" | sort)

echo "# Monthly Digest — ${MONTH}" > "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "**Generated**: $(date -u)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Summary stats
TOTAL_DAYS=${#DAILY_FILES[@]}
echo "## Overview" >> "$REPORT_FILE"
echo "- Days with digests: $TOTAL_DAYS" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Content and research counts
TOTAL_CONTENT=0
TOTAL_RESEARCH=0
for f in "${DAILY_FILES[@]}"; do
  # Count content entries (lines starting with "- content/" or content file lines)
  CONTENT_COUNT=$(grep -c '^- content/' "$f" || true)
  RESEARCH_COUNT=$(grep -c '^- research/' "$f" || true)
  TOTAL_CONTENT=$((TOTAL_CONTENT + CONTENT_COUNT))
  TOTAL_RESEARCH=$((TOTAL_RESEARCH + RESEARCH_COUNT))
done
echo "- Total content items produced: $TOTAL_CONTENT" >> "$REPORT_FILE"
echo "- Total research reports written: $TOTAL_RESEARCH" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Dev commits for the month
echo "## Dev Commits (month)" >> "$REPORT_FILE"
dev_commits=$(git log --since="${MONTH}-01" --until="${MONTH}-31 23:59:59" --pretty=format:'%s' 2>/dev/null | grep '^dev:' | sed 's/^/- /' || true)
if [ -n "$dev_commits" ]; then
  echo "$dev_commits" >> "$REPORT_FILE"
else
  echo "- (none)" >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# Daily breakdown
echo "## Daily Breakdown" >> "$REPORT_FILE"
for f in "${DAILY_FILES[@]}"; do
  DAY=$(basename "$f" | cut -d'-' -f1-3)
  CONTENT_COUNT=$(grep -c '^- content/' "$f" || true)
  RESEARCH_COUNT=$(grep -c '^- research/' "$f" || true)
  echo "- ${DAY}: ${CONTENT_COUNT} content, ${RESEARCH_COUNT} research" >> "$REPORT_FILE"
done
echo "" >> "$REPORT_FILE"

# Link to daily digests section
echo "## Daily Digest Links" >> "$REPORT_FILE"
for f in "${DAILY_FILES[@]}"; do
  DAY=$(basename "$f" | cut -d'-' -f1-3)
  echo "- [${DAY}](${f})" >> "$REPORT_FILE"
done
echo "" >> "$REPORT_FILE"

# Footer
echo "---" >> "$REPORT_FILE"
echo "*Generated by scripts/generate-monthly-digest.sh*" >> "$REPORT_FILE"

# Output to stdout
cat "$REPORT_FILE"
