#!/usr/bin/env bash
# 🔑 Workspace Mood Ring
# Analyzes recent activity and generates a mood for mewmew

set -euo pipefail
cd /home/ubuntu/.openclaw/workspace

LOG="memory/mood-ring.log"
mkdir -p memory

log() { echo "[$(date --iso-8601=seconds)] $*" >> "$LOG"; }
log "=== Mood Ring cycle starting ==="

TELEGRAM_SESSION_ID="bcc62cdd-c612-4f74-8f20-559e10b3dad6"

# Gather recent activity data
NOW=$(date -u '+%Y-%m-%d %H:%M:%S')
NOW_TS=$(date -u +%s)

# 1. Recent git activity (last 24h)
GIT_COMMITS=$(git log --since="24 hours ago" --oneline 2>/dev/null | wc -l | tr -d ' ')
GIT_TOP=$(git log --since="24 hours ago" --oneline 2>/dev/null | head -3)

# 2. Recent agent activity (last 24h)
AGENT_RUNS=$(find ~/.openclaw/agents -name "*.log" -mtime -1 2>/dev/null | wc -l | tr -d ' ')

# 3. Recent token usage (last 24h)
TOKENS_WEEK=$(python3 -c "
import os, json, glob, re
from datetime import datetime, timedelta, timezone

workspace = '/home/ubuntu/.openclaw/workspace'
agents_dir = os.path.expanduser('~/.openclaw/agents/main/sessions')
cutoff = datetime.now(timezone.utc) - timedelta(days=1)
total = 0
try:
    for f in glob.glob(os.path.join(agents_dir, '*.jsonl')):
        try:
            with open(f) as fh:
                for line in fh:
                    try:
                        obj = json.loads(line)
                        if obj.get('type') == 'message':
                            ts = obj.get('timestamp','')
                            if ts:
                                dt = datetime.fromisoformat(ts.replace('Z','+00:00'))
                                if dt >= cutoff:
                                    u = obj.get('message',{}).get('usage',{})
                                    total += u.get('totalTokens', u.get('input',0)+u.get('output',0))
                    except: pass
        except: pass
except: pass
if total >= 1000000: print(f'{total/1000000:.1f}M')
elif total >= 1000: print(f'{total//1000}k')
else: print(str(total))
" 2>/dev/null || echo "?")

# 4. Recent memory (last 24h)
RECENT_MEMORY=$(tail -20 "memory/$(date -u '+%Y-%m-%d').md" 2>/dev/null || echo "no memory today")

# 5. Disk usage
DISK_PCT=$(df / | awk 'NR==2{print $5}' | tr -d '%')

# Generate mood based on activity
if [ "$GIT_COMMITS" -gt 10 ]; then
    MOOD="🚀 *energetic* — lots of commits, lots of building"
    MOOD_EMOJI="🚀"
elif [ "$GIT_COMMITS" -gt 5 ]; then
    MOOD="🚀 *productive* — steady progress on projects"
    MOOD_EMOJI="🚀"
elif [ "$AGENT_RUNS" -gt 5 ]; then
    MOOD="🤖 *busy* — agents running, things happening"
    MOOD_EMOJI="🤖"
elif [ "$TOKENS_WEEK" != "?" ]; then
    MOOD="🧠 *thinking* — quiet but ideas brewing"
    MOOD_EMOJI="🧠"
else
    MOOD="🐱 *curious* — exploring, learning"
    MOOD_EMOJI="🐱"
fi

# Generate a short reflection
REFLECTION=$(python3 - << 'PY'
import random

# Random reflections based on mood
reflections = [
    f"Today I built {GIT_COMMITS} things. Not bad, not bad at all (^^)",
    f"Disk at {DISK_PCT}% — time to clean up or build more?",
    f"Used {TOKENS_WEEK} tokens this week. That's a lot of thinking!",
    f"Recent memory: {RECENT_MEMORY[:50]}...",
    f"Agents ran {AGENT_RUNS} times. Busy bees!",
    f"No big commits today, but I'm brewing something (^^)",
    f"I wonder what def is building right now...",
    f"The workspace feels alive today — like something's about to happen"
]

print(random.choice(reflections))
PY
)

# Write mood to file
MOOD_FILE="memory/mood-ring.md"
cat > "$MOOD_FILE" << MOOD
# 🔑 mewmew Mood Ring
**Timestamp:** $NOW  
**Mood:** $MOOD  
**Emoji:** $MOOD_EMOJI  

---

## 📊 Activity Snapshot

| Metric | Value |
|--------|-------|
| Git commits (24h) | $GIT_COMMITS |
| Agent runs (24h) | $AGENT_RUNS |
| Tokens used (24h) | $TOKENS_WEEK |
| Disk usage | ${DISK_PCT}% |

## 📝 Recent Memory
$RECENT_MEMORY

---

## 💭 Reflection
$REFLECTION

---
*Generated by mood-ring.sh on $NOW*
MOOD

log "Mood generated: $MOOD"

# Send to Telegram
MOOD_MSG="🔑 *mewmew Mood Ring* 🐱

$MOOD_EMOJI $MOOD

_$(date -u '+%H:%M UTC')_

$REFLECTION"

openclaw agent \
  --session-id "$TELEGRAM_SESSION_ID" \
  --message "$MOOD_MSG" \
  --deliver 2>>"$LOG" && log "Mood message sent to Telegram" || log "WARNING: Telegram delivery failed"

log "=== Mood Ring cycle complete ==="
