#!/usr/bin/env bash
# obsidian-weekly — Generate a weekly summary note for Obsidian

set -euo pipefail

WORKSPACE="/home/ubuntu/.openclaw/workspace"
VAULT_DIR="${OBSIDIAN_VAULT:-$HOME/obsidian-vault}"
WEEKLY_DIR="$VAULT_DIR/Weekly"
mkdir -p "$WEEKLY_DIR"

# Determine current week (ISO week number) and date range
YEAR=$(date +%Y)
WEEK=$(date +%V)
MONDAY=$(date -d "monday this week" +%Y-%m-%d)
SUNDAY=$(date -d "sunday this week" +%Y-%m-%d)
NOTE_NAME="${YEAR}-W${WEEK} (${MONDAY} to ${SUNDAY})"
NOTE_FILE="$WEEKLY_DIR/${NOTE_NAME}.md"

# Count research and content this week
RESEARCH_COUNT=$(find research -name "*.md" -newermt "$MONDAY" ! -newermt "$(date -d "$SUNDAY +1 day" +%Y-%m-%d)" 2>/dev/null | wc -l)
CONTENT_COUNT=$(find content -name "*.md" -newermt "$MONDAY" ! -newermt "$(date -d "$SUNDAY +1 day" +%Y-%m-%d)" 2>/dev/null | wc -l)

# Top research (by filename, assuming sorted by date in name)
TOP_RESEARCH=$(ls research/*.md 2>/dev/null | tail -5 | xargs -I{} basename {} .md | sed 's/^/- [[&]]/')

# Upcoming holidays (next 14 days)
HOLIDAYS=$(./quick holidays 2>/dev/null | head -10 | sed 's/^/ - /')

cat > "$NOTE_FILE" <<EOF
# Week ${YEAR}-W${WEEK} Summary

**Period:** ${MONDAY} — ${SUNDAY}  
**Generated:** $(date -u '+%Y-%m-%d %H:%M UTC')

## 📊 Stats

- Research reports this week: **${RESEARCH_COUNT}**
- Content digests this week: **${CONTENT_COUNT}**
- Total disk usage: $(df -h "$VAULT_DIR" | awk 'NR==2 {print $5 " used"}')

## 📈 Top Recent Research

$( [ -n "$TOP_RESEARCH" ] && echo "$TOP_RESEARCH" || echo "*No research files yet*" )

## 🏖️ Upcoming Holidays

$( [ -n "$HOLIDAYS" ] && echo "$HOLIDAYS" || echo "*No upcoming holidays*" )

## 🔍 Quick Links

- [[Dashboard]] — live stats
- [[Research Index]] — browse all research
- [[Research Gaps]] — what's next

## 💭 Notes

*Add your reflections here...*

---

*Auto‑generated by OpenClaw obsidian‑weekly script*
EOF

echo "✓ Weekly summary created: $NOTE_FILE"
