#!/usr/bin/env python3
"""
Content Gardener - Generates blog posts and articles from seed topics.
This script is run periodically by the content-gardener-cron cron job.
"""

import json
import os
import sys
import datetime
import random
import requests  # pip install requests

# Configuration
WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT_DIR = os.path.join(WORKSPACE, 'content')
SEEDS_FILE = os.path.join(WORKSPACE, 'agents', 'seeds.json')
LOG_FILE = os.path.join(WORKSPACE, 'memory', 'content-gardener.log')

# Ensure directories exist
os.makedirs(CONTENT_DIR, exist_ok=True)
os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

def log(msg):
    timestamp = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
    line = f'[{timestamp}] {msg}'
    with open(LOG_FILE, 'a') as f:
        f.write(line + '\n')
    print(line, flush=True)

def load_seeds():
    if os.path.exists(SEEDS_FILE):
        with open(SEEDS_FILE) as f:
            return json.load(f)
    return []

def generate_article_title(seed):
    # Simple title generation from seed
    return seed.get('title', seed.get('id', 'Untitled'))

def generate_article_content(seed):
    # Placeholder generator - in production this would use an LLM
    title = generate_article_title(seed)
    topics = seed.get('topics', [])
    return f"""# {title}

Generated on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Overview
This article explores the topic: {topics[0] if topics else 'Various AI developments'}

## Key Points
- Point 1: Overview of the concept
- Point 2: Technical implementation details
- Point 3: Impact and applications

## Further Reading
- Related research papers
- Industry reports
- Reference implementations

---
*Auto-generated by Content Gardener*
"""

def main():
    log('Starting content gardener execution')
    
    seeds = load_seeds()
    if not seeds:
        log('No seeds found - nothing to process')
        return
    
    processed_count = 0
    for seed in seeds:
        seed_id = seed.get('id', 'unknown')
        try:
            title = generate_article_title(seed)
            content = generate_article_content(seed)
            
            # Create filename-safe title
            safe_title = title[:80].replace(' ', '-').replace('/', '-')
            filename = f"{datetime.date.today()}-{safe_title}.md"
            filepath = os.path.join(CONTENT_DIR, filename)
            
            with open(filepath, 'w') as f:
                f.write(content)
            
            log(f'Content written to {filepath}')
            processed_count += 1
            
        except Exception as e:
            log(f'Error processing seed {seed_id}: {str(e)}')
            continue
    
    log(f'Content gardener completed: {processed_count}/{len(seeds)} articles generated')

if __name__ == '__main__':
    main()