#!/usr/bin/env python3
import os, sys, json, datetime, subprocess, timezone
from pathlib import Path
from collections import defaultdict

# Paths
GRAPH_FILE = Path('/home/ubuntu/.openclaw/workspace/memory/graph.json')
SEEDS_FILE = Path('/home/ubuntu/.openclaw/workspace/memory/seeds.jsonl')
REPORTS_DIR = Path('/home/ubuntu/.openclaw/workspace/reports')
OPENCLAWS = '/home/ubuntu/.npm-global/bin/openclaw'

REPORTS_DIR.mkdir(parents=True, exist_ok=True)

def log(msg):
    print(f"[{datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}] {msg}")

def load_graph():
    if GRAPH_FILE.exists():
        with open(GRAPH_FILE) as f:
            return json.load(f)
    return {"nodes": [], "edges": []}

def load_seeds():
    seeds = []
    if SEEDS_FILE.exists():
        with open(SEEDS_FILE) as f:
            for line in f:
                line = line.strip()
                if line:
                    seeds.append(json.loads(line))
    return seeds

def find_today_nodes():
    today = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d')
    graph = load_graph()
    seeds_today = []
    outputs_today = []
    # Find seeds with ts containing today
    all_seeds = load_seeds()
    for seed in all_seeds:
        if seed.get('ts', '').startswith(today):
            seeds_today.append(seed)
    # Find output nodes created today (by filename date prefix)
    for node in graph.get('nodes', []):
        ntype = node.get('type')
        if ntype in ('output', 'content', 'app'):  # include all grown artifacts
            node_id = node.get('id', '')
            if isinstance(node_id, str):
                fname = Path(node_id).name
                if fname.startswith(today):
                    outputs_today.append(node)
    return seeds_today, outputs_today

def generate_harvest_report(seeds, outputs):
    today = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d')
    report_path = REPORTS_DIR / f"daily-harvest-{today}.md"
    lines = [
        f"# Daily Harvest — {today}",
        "",
        f"**Seeds gathered today:** {len(seeds)}",
        f"**Outputs produced today:** {len(outputs)}",
        "",
        "## Seeds"
    ]
    if seeds:
        for s in seeds:
            lines.append(f"- {s.get('title')} (source: {s.get('source')})")
    else:
        lines.append("- No seeds gathered today.")
    lines.append("\n## Outputs")
    if outputs:
        for o in outputs:
            title = o.get('title', o.get('id'))
            lines.append(f"- [{title}]({o.get('id')})")
    else:
        lines.append("- No outputs produced today.")
    lines.append("\n---\n*Auto‑generated by AI Garden Harvester*")
    content = "\n".join(lines)
    with open(report_path, 'w') as f:
        f.write(content)
    return report_path

def send_telegram_summary(seeds, outputs):
    summary = f"🌱 Daily Harvest — {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d')}\n"
    summary += f"• Seeds: {len(seeds)}\n"
    summary += f"• Outputs: {len(outputs)}\n"
    if outputs:
        summary += "New outputs:\n"
        for o in outputs[:5]:
            title = o.get('title', o.get('id'))
            summary += f"  - {title}\n"
    # Send via openclaw message (uses last chat)
    try:
        subprocess.run([OPENCLAWS, 'message', 'send', '--to', 'last', '--text', summary], timeout=30)
    except Exception as e:
        log(f"Telegram send failed: {e}")

def main():
    log("Harvester starting")
    seeds, outputs = find_today_nodes()
    log(f"Found {len(seeds)} seeds, {len(outputs)} outputs for today")
    report_path = generate_harvest_report(seeds, outputs)
    log(f"Report written to {report_path}")
    send_telegram_summary(seeds, outputs)
    log("Harvest complete")

if __name__ == '__main__':
    main()
