#!/bin/bash
# LinkedIn Content Agent - IBM Planning Analytics (Educational v3)
# Generates helpful, non-promotional posts: features, tips, tutorials, upcoming capabilities

LOGFILE="/home/ubuntu/.openclaw/workspace/memory/linkedin-pa-agent.log"
WORKSPACE="/home/ubuntu/.openclaw/workspace"
OUTPUT_DIR="$WORKSPACE/content"

log() {
  echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC') - $*" | tee -a "$LOGFILE"
}

log "Starting LinkedIn PA educational content cycle"

DATE=$(date -u +%Y-%m-%d)
YEAR=$(date -u +%Y)

# Gather feature/roadmap info
log "Researching IBM Planning Analytics features and roadmap..."
RESEARCH_OUTPUT="/tmp/pa-research-$(date +%s).txt"

# Focus on official docs, roadmap, tips
web_search --count 8 "IBM Planning Analytics Workspace features tips tricks tutorial $YEAR" > "$RESEARCH_OUTPUT" 2>&1 || true
web_search --count 6 "IBM Planning Analytics roadmap upcoming features 2026" >> "$RESEARCH_OUTPUT" 2>&1 || true
web_search --count 6 "IBM Planning Analytics best practices TM1 modeling" >> "$RESEARCH_OUTPUT" 2>&1 || true

# Fetch a few key URLs for depth
URLS=$(grep -o 'https://[^"]*' "$RESEARCH_OUTPUT" | grep -i ibm | head -4)
for url in $URLS; do
  log "Fetching: $url"
  web_fetch --extractMode text --maxChars 2500 "$url" >> "$RESEARCH_OUTPUT" 2>&1 || true
done

# Extract key nuggets: features, tips, upcoming
FEATURES=$(grep -iE 'feature|enhancement|new|improved' "$RESEARCH_OUTPUT" | head -8 | sed 's/^[[:space:]]*//')
TIPS=$(grep -iE 'tip|trick|best practice|how to|guide' "$RESEARCH_OUTPUT" | head -6 | sed 's/^[[:space:]]*//')
UPCOMING=$(grep -iE 'roadmap|planned|coming soon|Q[1-4]|2026' "$RESEARCH_OUTPUT" | head -5 | sed 's/^[[:space:]]*//')

# Build content
POST_DATE="$DATE-linkedin-pa-post.md"
POST_FILE="$OUTPUT_DIR/$POST_DATE"

# Choose focus area randomly or rotate: features, upcoming, tips, tutorial
FOCUS=$(echo "$FEATURES" | wc -l)
if [ "$FOCUS" -gt 0 ]; then
  # Build a Feature Spotlight post
  FEATURE_HIGHLIGHT=$(echo "$FEATURES" | head -1)
  POST_CONTENT="## 🛠️ IBM Planning Analytics Feature Spotlight

Did you know about **$FEATURE_HIGHLIGHT**?

In the latest releases (Workspace 3.1.4+), IBM Planning Analytics introduces capabilities that make planning faster and more intuitive:

- Explain Cell now shows up to 6 months of transactional detail — no more jumping to separate tools for context
- Custom Agents (PAaaS) let you automate workflows using MCP tools
- Guided import reusability saves hours on repetitive data loads
- Dimension copy supports up to 50,000 members as hierarchies

These might seem like small tweaks, but they dramatically improve the daily experience for FP&A teams.

---

💡 **Quick tip:** To enable Custom Agents, make sure you're on PAaaS with Workspace 2.1.17/3.1.4 or later. Check the IBM docs for the MCP tool list.

**What's your favorite PA feature that boosted productivity?** Share below!

#PlanningAnalytics #IBM #EnterpriseAnalytics #Finance #Productivity"
else
  # Fallback: tutorial-style
  POST_CONTENT="## 📘 IBM Planning Analytics Mini-Tutorial

Today let's cover a practical skill: **using the new Explain Cell feature** to speed up analysis.

1. Open a book or cube view
2. Right‑click a cell with a value
3. Select 'Explain Cell' → you'll now see up to 6 months of underlying transactions
4. Drill through directly without leaving the workspace

This is a game-changer for month‑end close analysis. You can quickly trace why a number changed without exporting to Excel.

---

🔧 **Pro tip:** Pin the Explain Cell pane so it stays visible while you navigate. Combine with bookmarks to document common analysis paths.

Have you tried this yet? Let me know how it impacts your workflow!

#PlanningAnalytics #Tutorial #Finance #BusinessIntelligence #Tips"
fi

cat > "$POST_FILE" << EOF
# IBM Planning Analytics LinkedIn Post (Educational)

**Date:** $DATE  
**Agent:** linkedin-pa-agent (educational focus)  
**Content type:** Feature spotlight / tutorial

$POST_CONTENT

---

*Sources: IBM Planning Analytics documentation, release notes, community blogs*  
*Generated by LinkedIn PA Agent — no promotional language, just useful insights.*

EOF

log "LinkedIn content saved to: $POST_FILE"

# Digest
DIGEST_FILE="$OUTPUT_DIR/$DATE-linkedin-pa-digest.md"
cat > "$DIGEST_FILE" << EOF
# LinkedIn Content Digest — IBM Planning Analytics (Educational)

**Date:** $DATE  
**Agent:** linkedin-pa-agent v3 (educational)  
**Content type:** Feature spotlight / tutorial

## Today's Post
- File: $(basename "$POST_FILE")
- Focus: Practical tips and capabilities (not sales-focused)
- Key message: Highlight a specific feature or workflow improvement

## Research Nuggets Used
- Features: $(echo "$FEATURES" | wc -l) found
- Tips: $(echo "$TIPS" | wc -l) found
- Upcoming: $(echo "$UPCOMING" | wc -l) found

## Recommendation
- Engage with comments by offering additional tips
- Ask readers to share their own shortcuts
- Consider follow-up posts addressing specific use cases

---

*End of digest*
EOF

log "Digest saved to: $DIGEST_FILE"

# Commit
cd "$WORKSPACE" || exit 1
if git status --porcelain | grep -q content/$DATE-linkedin-pa; then
  git add content/$POST_DATE content/$DATE-linkedin-pa-digest.md
  git commit -m "content: LinkedIn PA educational post for $DATE

- Feature spotlight / tutorial style (non-promotional)
- Highlights specific PA capabilities and practical tips
- Designed to spark discussion and knowledge sharing"
  log "Committed LinkedIn content to Git"
else
  log "No changes to commit"
fi

# Sync to Obsidian
if [ -f "$WORKSPACE/scripts/obsidian-sync.sh" ]; then
  "$WORKSPACE/scripts/obsidian-sync.sh" >> "$LOGFILE" 2>&1 || true
fi

log "LinkedIn PA agent cycle completed"
exit 0
