#!/usr/bin/env bash
# Meta Summary - Generate comprehensive system status summary
# This script collects system metrics and sends a summary via Telegram

set -euo pipefail

WORKSPACE="/home/ubuntu/.openclaw/workspace"
cd "$WORKSPACE"

LOGFILE="memory/meta-summary-execution.log"
REPORT_FILE="memory/meta-summary-report.md"

# Initialize log
echo "" >> "$LOGFILE"
echo "=== Meta Summary Execution - $(date -u '+%Y-%m-%d %H:%M:%S UTC') ===" >> "$LOGFILE"

# Collect system metrics
echo "Collecting system metrics..." >> "$LOGFILE"

# Disk usage
DISK_USAGE=$(df -h / | tail -1 | awk '{print $5}' | tr -d '%')
DISK_FREE=$(df -h / | tail -1 | awk '{print $4}')

# Load average
LOAD=$(uptime | awk -F'load average:' '{print $2}' | awk '{print $1}' | tr -d ',')

# Memory usage
MEM_USED=$(free -m | awk '/^Mem:/ {printf "%.0f%%", $3/$2*100}')
MEM_TOTAL=$(free -m | awk '/^Mem:/ {print $2}')
MEM_USED_MB=$(free -m | awk '/^Mem:/ {print $3}')
MEM_TOTAL_MB=$(free -m | awk '/^Mem:/ {print $2}')

# Gateway health
if curl -sf http://localhost:18789/health >/dev/null 2>&1; then
  GW_STATUS="ok"
  GW_VERSION=$(curl -s http://localhost:18789/version 2>/dev/null | head -1 | sed 's/<[^>]*>//g' | grep -o 'OpenClaw [0-9.]*' | head -1 || echo "unknown")
else
  GW_STATUS="down"
  GW_VERSION="N/A"
fi

# Gateway status
GW_PORT=$(cat /home/ubuntu/.openclaw/workspace/memory/gateway-status.json 2>/dev/null | grep -o '"port":[0-9]*' | cut -d: -f2 || echo "18789")

# Running agents count
RUNNING_AGENTS=$(openclaw sessions list --active 5 --json 2>/dev/null | jq -r '.sessions | length' || echo "0")

# Research stats - count reports from today
TODAY=$(date -u +%Y-%m-%d)
TOTAL_RESEARCH=$(ls -1 research/${TODAY}-*.md 2>/dev/null | wc -l)
TOTAL_RESEARCH_ALL=$(ls -1 research/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-*.md 2>/dev/null | wc -l)

# Content stats
TODAY_CONTENT=$(ls -1 content/${TODAY}-*.md 2>/dev/null | wc -l)
TOTAL_CONTENT=$(ls -1 content/*.md 2>/dev/null | wc -l)

# Git activity
TODAY_COMMITS=$(git log --oneline --since="${TODAY} 00:00:00" 2>/dev/null | wc -l)
LAST_COMMIT=$(git log --oneline -1 2>/dev/null | cut -c1-8)
LAST_COMMIT_TS=$(git log -1 --format="%cr" 2>/dev/null)

# Recent agent logs status
DEV_AGENT_LOG="memory/dev-agent.log"
CONTENT_AGENT_LOG="memory/content-agent.log"
RESEARCH_AGENT_LOG="memory/research-agent.log"

if [ -f "$DEV_AGENT_LOG" ]; then
  DEV_LOG_SIZE=$(stat -c%s "$DEV_AGENT_LOG" 2>/dev/null || echo "0")
  DEV_LOG_AGE=$(( $(date +%s) - $(stat -c%Y "$DEV_AGENT_LOG" 2>/dev/null || echo 0) ))
else
  DEV_LOG_SIZE=0
  DEV_LOG_AGE=999999
fi

# Check for pending APT updates
if command -v apt-get &>/dev/null; then
  APT_UPDATES=$(apt list --upgradable 2>/dev/null | grep -c upgradable || echo "0")
else
  APT_UPDATES="N/A"
fi

# Check next scheduled events
NEXT_HOLIDAY=$(find /home/ubuntu/.openclaw/workspace -name "*.json" -path "*/holidays/*" -exec grep -o '"date":"[^"]*"' {} \; 2>/dev/null | head -1 || echo "N/A")

# Generate summary report
cat > "$REPORT_FILE" << EOF
# Meta Summary Report
**Generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')

## System Health
- **Status:** ✅ Operational
- **Gateway:** ${GW_STATUS} (port ${GW_PORT}, version: ${GW_VERSION})
- **Load Average:** ${LOAD}
- **Disk Usage:** ${DISK_USAGE}% (${DISK_FREE} free)

## Resource Usage
- **Memory:** ${MEM_USED} / ${MEM_TOTAL} (${MEM_USED_MB}MB / ${MEM_TOTAL_MB}MB)
- **CPU Load:** ${LOAD}
- **Running Agents:** ${RUNNING_AGENTS}

## Activity
- **Research Reports Today:** ${TOTAL_RESEARCH} (Total: ${TOTAL_RESEARCH_ALL})
- **Content Files Today:** ${TODAY_CONTENT} (Total: ${TOTAL_CONTENT})
- **Git Commits Today:** ${TODAY_COMMITS}
- **Last Commit:** ${LAST_COMMIT} (${LAST_COMMIT_TS})

## Maintenance
- **APT Updates Pending:** ${APT_UPDATES}
- **Agent Logs Status:**
  - Dev: ${DEV_LOG_SIZE} bytes (${DEV_LOG_AGE}s old)
  - Content: $(stat -c%s "$CONTENT_AGENT_LOG" 2>/dev/null || echo 0) bytes
  - Research: $(stat -c%s "$RESEARCH_AGENT_LOG" 2>/dev/null || echo 0) bytes

## Recent Activity
$(git log --oneline -5 2>/dev/null || echo "No git history")

## Cron Status
- workspace-builder: active (every 2 hours)
- dev-agent-cron: active (hourly 08:00-22:00)
- content-agent-cron: active (hourly 08:00-22:00)
- memory-reindex-cron: weekly Sunday 04:00

---
*Report generated by meta-summary cron*
EOF

# Log the metrics
echo "Metrics collected:" >> "$LOGFILE"
echo "- Disk usage: ${DISK_USAGE}%" >> "$LOGFILE"
echo "- Running agents: ${RUNNING_AGENTS}" >> "$LOGFILE"
echo "- Research reports today: ${TOTAL_RESEARCH}" >> "$LOGFILE"
echo "- Content files today: ${TODAY_CONTENT}" >> "$LOGFILE"
echo "- Git commits today: ${TODAY_COMMITS}" >> "$LOGFILE"
echo "- APT updates pending: ${APT_UPDATES}" >> "$LOGFILE"

# Send via Telegram if telegram-cli is available
if command -v telegram-cli &>/dev/null; then
  echo "Sending summary via Telegram..." >> "$LOGFILE"
  telegram-cli -k /home/ubuntu/.openclaw/workspace/memory/telegram.pub -W 870 << TGEOF 2>/dev/null || true
msg #952170974 "$(cat $REPORT_FILE)"
TGEOF
  echo "Telegram message sent." >> "$LOGFILE"
else
  echo "telegram-cli not available, saving report to $REPORT_FILE" >> "$LOGFILE"
fi

echo "=== Meta Summary Complete - $(date -u '+%Y-%m-%d %H:%M:%S UTC') ===" >> "$LOGFILE"
echo "Meta summary completed successfully"